version: '3.8'
services:
    oracle-server-db:
      container_name: oracle-server-db
      image: gvenzl/oracle-xe
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==worker]
      ports:
        - "1521:1521"
        - "1522:1522"
      environment:
        ORACLE_PASSWORD: "123"
    
